import sys
import pymysql
import pandas as pd
from ollama import chat
from intent import get_intent_sql

schema = """
Table: consumer_data

Columns:
consumer_no
division
location_code
group_no
rd_no
consumer_name
consumer_status
tariff_category
address1
address2
mobile_no
net_bill
arrear
billed_unit
"""

question = sys.argv[1]

# ==========================
# FIRST TRY INTENT
# ==========================

sql_query = get_intent_sql(question.lower())

if sql_query:

    print("Your Result Is Generated By Intent")

else:

    prompt = f"""
Generate only MySQL query.

{schema}

Examples:

Question:
Show top 10 consumers having highest arrears

SQL:
SELECT location_code,group_no,rd_no,consumer_no,
consumer_name,address1,address2,mobile_no,
arrear,net_bill
FROM consumer_data
ORDER BY arrear DESC
LIMIT 10;

Question:
Show top 10 consumers having highest arrears for active consumer

SQL:
SELECT location_code,group_no,rd_no,consumer_no,
consumer_name,address1,address2,mobile_no,
arrear,net_bill
FROM consumer_data
WHERE consumer_status='ACTIVE'
ORDER BY arrear DESC
LIMIT 10;

Question:
Show top 10 consumers having highest bill

SQL:
SELECT location_code,group_no,rd_no,consumer_no,
consumer_name,address1,address2,mobile_no,
net_bill
FROM consumer_data
ORDER BY net_bill DESC
LIMIT 10;

Question:
{question}
"""

    response = chat(
        model='phi3:mini',
        messages=[
            {
                'role': 'user',
                'content': prompt
            }
        ]
    )

    sql_query = response['message']['content']
    sql_query = sql_query.replace("```sql", "")
    sql_query = sql_query.replace("```", "")
    sql_query = sql_query.strip()

    print("Your Result Is Generated By AI")

# ==========================
# SHOW SQL
# ==========================

print("\nGenerated SQL:")
print(sql_query)

# ==========================
# MYSQL CONNECTION
# ==========================

conn = pymysql.connect(
    host="localhost",
    user="root",
    password="",
    database="consumer_db"
)

try:

    df = pd.read_sql(sql_query, conn)

    df.to_excel("result.xlsx", index=False)

    print(df.to_html(index=False))

except Exception as e:

    print("Error:", e)

finally:

    conn.close()